# pyproject.toml
[tool.coverage.run]
source = ["Day01", "Day02", "Day03", "Day04", "Day05", "Day06", "Day07", "Day08"]
[tool.pytest.ini_options]
addopts = "--cov --cov-report=lcov:lcov.info --cov-report=term"