[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.0.0"
petgraph = "0.6.5"

[dev-dependencies]
rstest = "0.23.0"
assert_cmd = "2.0"

[[bin]]
name = "day18"
path = "src/main.rs"