# This is a basic workflow to help you get started with Actions

name: Julia Environment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '**.jl'
  pull_request:
    branches: [ master ]
    paths:
      - '**.jl'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: 2020/Day21-Allergen_Assessment
    strategy:
      matrix:
        julia-version: ['1']
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: julia -e 'import Pkg; Pkg.add("Match")'
      - run: julia -e 'import Pkg; Pkg.add("Test")'
      - run: julia -e 'import Pkg; Pkg.add("BenchmarkTools")'
      - run: julia -e 'println("Hello, World!")'
      - run: julia Day21.jl
 